### ISSUE TITLE
Your issue title here

### ISSUE THREAD

**Issue by Khalidalmasri** [gabrieltempass/ab-tester#3]
Your issue description here

**Comment by gabrieltempass** [comment]
Hi @Khalidalmasri ,

I got an empty issue from you, with no title and description. Do you want to comment something about the A/B Tester? I'm opened to feedback!

**Comment by gabrieltempass** [comment]
@Khalidalmasri I will close the issue, since it's blank. If you wish to request a bug fix, provide a feedback, ask for a feature or something else, you can open another one here:

[https://github.com/gabrieltempass/ab-tester/issues/new](https://github.com/gabrieltempass/ab-tester/issues/new?title=Your%20issue%20title%20here&body=Your%20issue%20description%20here)

Just remember to provide a title and a description to it. Thanks!
