### ISSUE TITLE
~><  >€ xyzzRUN SETup reboot

### ISSUE THREAD

**Issue by 187sec** [gabrieltempass/ab-tester#4]

**Comment by gabrieltempass** [comment]
Reboot the app doesn't solve the problem. Streamlit seems to have a bug, that is causing the app to crash:
https://discuss.streamlit.io/t/failed-to-download-the-sources-for-repository/29179/22

I'm waiting for a response from their developers. Meanwhile, I'm also trying to change how the dependencies are installed, since the error seems to be related to that. I will try switching to pipenv, instead of conda.

**Comment by gabrieltempass** [comment]
Switching from conda to pipenv solved the issue.
